import type { PageTransitionConfig } from "@/types/pageTransitionConfig";

export const pageTransitionConfig: PageTransitionConfig = {
	enable: true,
	timing: {
		enter: 180,
		open: 400,
		writeMin: 700,
		writeMax: 1320,
		writePerCharacter: 105,
		hold: 100,
		reveal: 300,
	},
	writing: {
		mode: "auto",
		style: "fountain",
		inkBleed: 0.48,
		penLift: true,
	},
	destinationLabels: {
		"/": "Home",
		"/dynamic/": "Notes",
		"/archive/": "Articles",
		"/calendar/": "Calendar",
		"/gallery/": "Gallery",
		"/music/": "Music",
		"/projects/": "Projects",
		"/reading/": "Reading List",
		"/about/": "About",
		"/about/me/": "About Me",
		"/about/site/": "About This Site",
		"/about/ling/": "Ling",
		"/me/": "About Me",
		"/search/": "Search",
		"/tags/": "Tags",
		"/categories/": "Categories",
		"/series/": "Series",
		"/friends/": "Friends",
		"/guestbook/": "Guestbook",
		"/booknav/": "Book Navigation",
		"/bangumi/": "Anime",
		"/myanimelist/": "Anime List",
		"/bilibili/": "Bilibili",
		"/vndb/": "Visual Novels",
		"/sponsor/": "Support",
		"/atom/": "Atom Feed",
		"/rss/": "RSS Feed",
	},
};
