// Internal puzzle data. Answers are not rendered as visitor-facing hints.
export const pulsePuzzle = {
	storageKey: "demiur-pulse-puzzle-v6",
	previousStorageKey: "demiur-pulse-puzzle-v5",
	legacyStorageKey: "demiur-pulse-puzzle-v4",
	olderStorageKey: "demiur-pulse-puzzle-v3",
	oldestStorageKey: "demiur-pulse-puzzle-v2",
	firstStorageKey: "demiur-pulse-puzzle-v1",
	version: 6,
	multiplier: 5,
	offset: 8,
	alphabetSize: 26,
	// The URL itself is a clue, not an access token or a second progress gate.
	holdHint: {
		word: "HOLDING",
		base64url: "SE9MRElORw",
	},
	clues: [
		{
			id: "home",
			order: "01",
			cipher: "05",
			style: "fold",
			hint: "折角的铅笔字：这张纸，好像从一份旧借阅凭条上落下",
		},
		{
			id: "archive",
			order: "03",
			cipher: "11",
			style: "ticket",
			hint: "凭条背面：剩下的日期，被收进了按年月排列的册子",
		},
		{
			id: "categories",
			order: "05",
			cipher: "02",
			style: "pencil",
			hint: "页边的字迹：有一枚印记，留在记录每一天的地方",
		},
		{
			id: "tags",
			order: "02",
			cipher: "04",
			style: "stamp",
			hint: "褪色的印章旁：下一份索引，夹在那些通向工具的地址之间",
		},
		{
			id: "posts",
			order: "04",
			cipher: "20",
			style: "index",
			hint: "索引背面：把记录带到唱针沉默的地方",
		},
	],
	scraps: [
		{ id: "scrap-af", fragment: "AF", number: "5", side: "left" },
		{ id: "scrap-fine", fragment: "FINE", number: "8", side: "right" },
	],
	scrapDescription:
		"被撕掉一块的便签，上面留着数字与半个单词。撕口似乎还可以对上",
	worldAnswer: "NEWWORLD",
	starfieldAnswer: "PALINGENESIS",
	worldQuestion: { afterLine: 3, label: "你是谁？" },
	worldDialogue: [
		{ speaker: "？？？", text: "停下吧，再往前会有危险的" },
		{ speaker: "？？？", text: "……" },
		{ speaker: "？？？", text: "你不是帕林杰斯的人，是怎么来到帕林杰斯的？" },
		{ speaker: "？？？", text: "等等，我明白了，你和那家伙来自同一个世界" },
		{
			speaker: "？？？",
			text: "用那家伙的话来说，应该是开启新“世界”的人、“世界”的支柱之类的吧",
		},
		{ speaker: "？？？", text: "虽然我不能放任可以穿越世界的这种危险存在" },
		{
			speaker: "？？？",
			text: "但是既然你和那家伙来自同一个世界，那就没什么问题了",
		},
		{ speaker: "？？？", text: "……" },
		{
			speaker: "？？？",
			text: "他竟然在帕林杰斯开了一个可以导向这里的通道吗？",
		},
		{
			speaker: "？？？",
			text: "唉，真是乱来，他最好只开了这一个通道，也只打算开这一个",
		},
		{
			speaker: "？？？",
			text: "（低声）不过以他的性格，他肯定还开了别的通道，真是给我找麻烦",
		},
		{ speaker: "？？？", text: "你该离开了，再待下去估计会受不了的" },
		{
			speaker: "？？？",
			text: "也许你已经知晓我是谁，也许永远也不会知晓，也许明天就会知晓",
		},
		{ speaker: "？？？", text: "那家伙也许会告诉你，也许不会" },
		{ speaker: "？？？", text: "至于现在，你该回去了" },
		{ speaker: "？？？", text: "终有一天，我们的思想会超越整个“世界”" },
		{ speaker: "？？？", text: "再会了……" },
	],
	// Public scene text selected from the local dialogue workbook's third sheet.
	// The workbook itself is private and must never be bundled or committed.
	echoDialogue: [
		{ speaker: "女声", text: "嗯————哼！" },
		{ speaker: "男声", text: "哎呀，我错了，别生气了好不好" },
		{ speaker: "女声", text: "都到那个时候了，还想逞英雄！如果你死掉了，我，我怎么还能活得下去呢……" },
		{ speaker: "男声", text: "（挠头声）额……好啦好啦，我这不是没死嘛，现在还老老实实站在你面前呢" },
		{ speaker: "男声", text: "（低声）还真是多亏了那个人啊，虽然还是没搞明白他是谁" },
		{ speaker: "旁白", text: "噗的一声，像是一人扑进了另一个人的怀里" },
		{ speaker: "女声", text: "真是的，绝对，绝对，绝对不要再像那样，抛下我了啊" },
		{ speaker: "男声", text: "不会的，夕月，再也不会了" },
		{ speaker: "夕月", text: "……再抱紧一些嘛，青，让我再多感受一下你" },
		{ speaker: "青", text: "嗯，好" },
		{ speaker: "旁白", text: "（沉默着）" },
		{ speaker: "青", text: "我说怎么感觉少了些什么，夕月，尾巴没有了的话，就没有办法抽我的大腿了呀，哈哈" },
		{ speaker: "夕月", text: "嗯？你说什么？！" },
		{ speaker: "青", text: "唉？！怎么，怎么尾巴又出现了？（“啪”的一声巨响）啊！！！！！" },
		{ speaker: "夕月", text: "笨蛋，只是把尾巴收起来了而已啊！" },
		{ speaker: "青", text: "嘻，可以和解吗？" },
		{ speaker: "旁白", text: "（打闹声、嬉笑声）" },
		{ speaker: "夕月", text: "呼……" },
		{ speaker: "青", text: "消……消气了吗？" },
		{ speaker: "夕月", text: "嗯————噗嗤，真是的，青，你这家伙……" },
		{ speaker: "夕月", text: "……最喜欢你了啊，青" },
		{ speaker: "青", text: "我也是，最喜欢你了，夕月" },
	],
} as const;
